- .dockerignore
- Dockerfile
Copy the plugin files to the default nginx assets directory. The gets the serving of plugin assets over HTTP working (not HTTPS yet).
Also add .dockerignore file to avoid copying unnecessary files during build steps.
> Fix nginx config for serving HTTP assets

- package.json
- yarn.lock
Since https://github.com/openshift/console/pull/13521 merged, plugins are expected to have an explicit @patternfly/react-icons dependency.
> Add @patternfly/react-icons to package.json

- console-extensions.json
- package.json
- src/components/GeneralPage.tsx
- src/hooks/useAlertExtension.ts
- src/hooks/usePodExtension.ts
- src/redux-actions.ts
- src/redux-reducers.ts
- yarn.lock
Adds an "Ask OpenShift Lightspeed" action to the Actions dropdown on the pod details page and to the kebab menu of the pods list page.
The callback is just a placeholder for now to show that the integration works.
Adds a redux store for the plugin, which allows passing data from the pod page to the OpenShift Lightspeed page.
> Add OLS action to pod Actions dropdown using redux

- src/components/GeneralPage.tsx
Clicking this button clears the current conversation so that the next prompt will become the start of a new conversation.
> OLS-356: Add "New chat" button that clears current chat and starts a new chat

- console-extensions.json
- src/components/GeneralPage.tsx
Enable for CronJob, DaemonSet, ReplicaSet and StatefulSet These all use the standard details page component in the web console, so we can reuse the existing `K8sResourceActionsProvider` code.
> Enable "Ask OpenShift Lightspeed" action on 4 more resource types

- src/components/GeneralPage.tsx
When a message is appended to the chat history, automatically scroll to the bottom so that the latest message is always visible.
> Add automatic scroll to bottom for chat messages

- src/components/GeneralPage.tsx
We don't want the frontend timing out before the backend, so set the timeout pretty high.
> Increase OLS API timeout to 10 minutes

- console-extensions.json
- locales/en/plugin__lightspeed-console-plugin.json
- package.json
- src/components/GeneralPage.tsx
With this change, OLS is only accessible using the popover UI.
> Remove separate OLS page from web console

- src/components/GeneralPage.tsx
Any current chat context (e.g. chatting about a k8s resource) should also be cleared when you start a new chat.
> Make "New Chat" button also clear any chat context

- charts/openshift-console-plugin/templates/consoleplugin.yaml
- charts/openshift-console-plugin/values.yaml
This currently uses `authorization: None`, but should be changed to
`authorization: UserToken` once the OLS API has auth set up.
> OLS-247: Add proxy config so UI can hit the OLS API

- src/components/GeneralPage.tsx
- src/redux-actions.ts
- src/redux-reducers.ts
Store the current prompt text in Redux instead of component state so that it is persisted when the popover is closed and reopened.
Also drop the default prompt text when chatting about a k8s resource.
> OLS-442: Move prompt text to Redux so it isn't lost when the popover is closed

- src/components/GeneralPage.tsx
- src/redux-actions.ts
- src/redux-reducers.ts
- src/types.ts
Store the user feedback in redux as part of the chat history so that we can store different user feedback for each response and persist it when the user feedback area is closed and when the whole OLS popover UI is closed.
Also converts the chat history in Redux from a standard Array to an Immutable List so that we can use the Immutable.js getIn function to extract specific fields from within the nested data.
> OLS-462: Implement separate user feedback for each response and move to redux

- src/components/GeneralPage.tsx
- src/components/general-page.css
Give the user feedback comment box and the "Thank you for your feedback" message the same margin.
Also removes unused CSS class `ols-plugin__feedback-label`
> Adjust user feedback margins

- src/components/GeneralPage.tsx
- src/components/general-page.css
- Make default prompt input height match the submit button height
- Automatically revert to default height after submitting prompt
- Reduce maximum prompt height a little
- Make the submit button square
> Improve prompt styling - mostly input height

- src/components/GeneralPage.tsx
- src/types.ts
Update to match the new format of the referenced documents in the response from the `query` endpoint.
Also add additional checks that the fields are strings as expected before attempting to render the document links.
> Fix handling of referenced documents

- src/components/GeneralPage.tsx
- src/components/general-page.css
Fix margins so that the "New chat" button is left aligned with the heading if it can't fit to the right of the heading.
> Fix "New chat" button margin

- src/components/GeneralPage.tsx
Still automatically scroll to the bottom of the existing chat history, but scroll instantly, not smoothly.
> Remove smooth scroll effect when UI is opened with existing history

- src/components/GeneralPage.tsx
Indicate that the prompt input is invalid if it is empty or contains only whitespace.
> Add prompt input validation to catch empty prompts

- src/components/ErrorBoundary.tsx
- src/components/Popover.tsx
Currently doesn't display a user visible error message, but logs the error details in the browser console since this is mostly for debugging.
> Add React error boundary to contain any thrown errors to the plugin

- src/attachments.ts
- src/components/Feedback.tsx
- src/components/GeneralPage.tsx
- src/components/general-page.css
- src/types.ts
In the chat history, show any attachments that were added to each prompt.
Also add a popover to the attachment labels (used both below the current prompt input and in the chat history). The popover shows the resource kind, name and namespace as well as the YAML that is actually attached to the prompt.
> OLS-534,OLS-555: Add attachments to chat history and add attachment details popover

- src/components/GeneralPage.tsx
- src/components/general-page.css
Improve truncation of the attachment labels so that the attachment type (currently YAML or Status YAML) is always visible.
> Improve attachment label truncation

- src/components/GeneralPage.tsx
Conceptually, this button's action is closer to minimizing the window than to closing the window. Especially since the chat history any currently entered text will be preserved.
> Change popover close icon from TimesIcon to WindowMinimizeIcon

- src/components/GeneralPage.tsx
- src/components/general-page.css
When there is no recognized context for the page, display a message that says that.
> OLS-535: Display attach menu on all pages

- src/components/GeneralPage.tsx
see discussion in https://issues.redhat.com/browse/OLS-531 for what motivated the change.
tldr: the LLM didn't actually have access to the entire doc to generate the response (only some section of that linked doc), and it may not have used any of the content. So listing the docs are "related" rather than "referenced" avoids creating a false impression
> OLS-531: Use looser phrasing for describing RAG references

- src/components/AttachLogModal.tsx
Fixes a bug with log attach modal where the container dropdown was sometimes not poulated with a default value.
> Fix attach log modal to always have a default value for the container

- src/components/GeneralPage.tsx
The alert attachments can only be YAML attachments, so we don't add a label in this case.
> Remove "YAML" label for alert attachments

- src/components/GeneralPage.tsx
- src/components/general-page.css
Code blocks can be scrolled if they don't fit in the max-height.
> OLS-690: Limit the height of code blocks in OLS responses

- package.json
Webpack version must match the version used by the plugin SDK
> Set webpack version override for npm

- package.json
- yarn.lock
react-markdown v9 requires a higher version of React than we are currently using.
> Downgrade react-markdown to v8 to resolve incompatibility warning

- src/attachments.ts
- src/components/AttachEventsModal.tsx
- src/components/AttachLogModal.tsx
- src/components/Feedback.tsx
- src/components/GeneralPage.tsx
- src/redux-actions.ts
- src/types.ts
So that OLS has enough context to know what each attachment belongs to, we now also include the resource's `kind` and `metadata` with the `status` YAML attachment.
Similarly, we previx log attachments with a line of text explaning which container and pod it belongs to.
Also removes the attachment's `options` data from redux since it is no longer used.
> OLS-717: Pass attachments in separate fields to OLS

- package-lock.json
- package.json
- yarn.lock
These are the latest versions that have backwards compatibility with version 4.15.x
> Downgrade plugin SDK packages to OpenShift 4.15 compatible versions

- src/components/GeneralPage.tsx
Now that responses are rendered with react-markdown, we don't want to apply `white-space: pre-line` to them.
> OLS-685: Fix for white space in OpenShift Lightspeed responses

- src/components/AttachEventsModal.tsx
- src/components/AttachLogModal.tsx
For the attach logs modal and the attach events modal, remove the tooltip above the Slider component. Instead show the currently selected count in the input label. This solves a problem where the tooltip would jitter as the slider was dragged. It also means the the count is always visible without having to hover over the slider.
> OLS-872: Remove tooltip from Sliders and add current count to labels instead

- README.md
Because we are not currently using Cypress tests in this repository, but are adding the tests in a separate repository.
> Remove mention of Cypress from README

- src/components/Feedback.tsx
- src/components/GeneralPage.tsx
- src/error.ts
- src/types.ts
Use the same logic for the `query` and `feedback` endpoints to catch all the possible errors for both endpoints.
> OLS-860: Fix display of OLS API error messages

- .tekton/lightspeed-console-pull-request.yaml
- .tekton/lightspeed-console-push.yaml
Removed sbom-json-check from Konflux pipelines as sbom-json-check task is getting deprecated.
> Removed sbom-json-check from Konflux pipelines

- src/components/AttachmentModal.tsx
- src/components/GeneralPage.tsx
- src/types.ts
The attachment modal should only allow editing the attachment if it is being viewed before submitting the prompt. When opened from the chat history, the Edit button should not be shown.
> OLS-989: Fix to hide Edit button for attachments in chat history

- src/components/AttachmentModal.tsx
Fixes a bug where the value of the attachment editor text was not updated after clicking the "Revert to original" button. This meant that the editor would save with the wrong value when following these steps:
1. Add any attachment to the prompt
2. Edit the attachment
3. Revert your edit
4. Edit the attachment again, but hit "Save" without actually changing the text
5. The attachment will have saved with the value from step (2)
> OLS-997: Fix attachment save with wrong value after revert

- locales/en/plugin__lightspeed-console-plugin.json
- src/components/AttachEventsModal.tsx
- src/components/AttachLogModal.tsx
- src/components/GeneralPage.tsx
Because these modals didn't call `onClose` when the components unmounted (e.g.  when you hit the browser back button to leave the page), the `isOpen` flag continued to be `true`. That meant that if you later returned to a page with the same modal (another pod details page), the modal would unexpectedly open.
Also makes sure we clear the attach events modal's `error` and `isLoading` state if the resource context changes. Currently, this shouldn't matter since changing the resource context only happens when you navigate to a different page, which would unmount the modal and clear the state anyway. However, it might be possible in the future.
> OLS-1000: Fix attach events and attach logs modals to call onClose on unmount

- src/components/GeneralPage.tsx
Enabled for the same set of resource types that have the attach YAML functionality (Pod, Job, CronJob, Deployment, DaemonSet, ReplicaSet and StatefulSet).
> OLS-998: Enable attach events functionality for additional k8s resource types

- src/components/AttachEventsModal.tsx
- src/components/GeneralPage.tsx
- src/redux-actions.ts
- src/redux-reducers.ts
Store the events data in redux so it can be shared between components.
> Disable "Events" in attach menu if there are no events

- src/components/AttachLogModal.tsx
- src/components/general-page.css
Before attaching logs to the prompt, you can now preview the log lines that will be attached in the modal.
> OLS-952: Add preview to the attach logs modal

- src/components/AttachLogModal.tsx
- src/components/Feedback.tsx
- src/components/GeneralPage.tsx
- Don't specifiy a timeout for loading alerts and container logs (use the Console's default timeout, which is currently 60 seconds)
- Reduce user feedback timeout to 5 minutes
> Reduce some API fetch timeouts

- src/components/AttachMenu.tsx
If you opened the attach menu, then used the browser back button to go to a page where the attach menu is disabled, the menu would remain open. This fixes it to automatically close in that case.
> Fix bug where attach menu could be open even when disabled

- .tekton/lightspeed-console-pull-request.yaml
- .tekton/lightspeed-console-push.yaml
- Dockerfile
Update the Konflux pipelines to remove enterprise contract warnings
JIRA: https://issues.redhat.com/browse/OLS-1151
> OLS-1151: Update the Konflux pipelines to remove enterprise contract warnings

- src/components/AttachEventsModal.tsx
- src/components/AttachLogModal.tsx
- src/components/general-page.css
Before attaching events to the prompt, you can now preview what will be attached in the modal.
> OLS-1143: Add preview to the attach events modal

- src/components/Popover.tsx
The Button component was only being used when the popover UI was closed. This changes it so that a Button is always used regardless of whether the popover UI is open or closed.
> OLS-1157: Always render the popover button with the Button component

- .tekton/lightspeed-console-pull-request.yaml
- .tekton/lightspeed-console-push.yaml
Reenable source image builds now that [KFLUXBUGS-1508](https://issues.redhat.com//browse/KFLUXBUGS-1508) is fixed
> Reenable source image builds now that KFLUXBUGS-1508 is fixed

- src/components/AttachEventsModal.tsx
- src/components/general-page.css
The code block had different spacing above and below depending on where it was used. This makes it more consistent.
In particular, this adds spacing around code blocks when they appear in the chat history.
> OLS-1249: Make spacing around code block more consistent

- src/components/AttachMenu.tsx
- src/hooks/useLocationContext.ts
Add the ability to attach YAML and events to the prompt for HorizontalPodAutoscalers.
Also reorder the resource types object to match the order they appear in the console navigation menu.
> OLS-1077: Add the YAML and Events attach options for HPAs

- src/components/AttachEventsModal.tsx
- src/components/AttachLogModal.tsx
It is not possible to leave these inputs empty, so it doesn't makes sense to add the isRequired indicator.
> OLS-1250: Remove the isRequired option for inputs that have a default value

- src/components/AttachEventsModal.tsx
Don't show the ticks if there will be too many because they get too squashed together and it's not clear that they are ticks.
> OLS-1251: Add ticks to attach events slider

- src/components/ImportAction.tsx
- src/types.ts
**_Note: PR openshift/console#14562 is dependant on this PR._**
**Type**: 
**Jira Link**: 
1. https://issues.redhat.com/browse/ODC-7711
**Solution Description**: 
This pull request includes changes to the `ImportAction` component and the `CodeBlock` type to track the source of code block imports. The most important changes are:
Enhancements to `ImportAction` component:
* [`src/components/ImportAction.tsx`](diffhunk://#diff-3ff6eed62347452b46e32a856ba102a861b068f556b5c9220bb76cb47588589fR46): Added a `triggeredFrom` property to the `importCodeBlock` function call to track the pathname from which the import was triggered.
Updates to `CodeBlock` type:
* [`src/types.ts`](diffhunk://#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR41): Added an optional `triggeredFrom` …
> ODC-7711: Add Telemetry to the OLS Import to Console feature

- locales/en/plugin__lightspeed-console-plugin.json
- src/components/AttachLogModal.tsx
- src/components/AttachMenu.tsx
Actually adds the logs for the HPA's `scaleTargetRef` resource.
Also fixes display of error message when the pods fail to load in the attach logs modal.
> OLS-1077: Add attach logs option for HPAs

- src/components/popover.css
This prevents the OpenShift Lightspeed floating button from obscuring elements on the page by ensuring that you can scroll the page far enough to bring any such elements above the button.
These CSS rules don't add bottom padding to all web console pages, but they do cover the majority of pages.
FYI @asuwebdesign, @gauravsingh85
> OLS-1343: Add padding to bottom of most web console pages

- src/components/ImportAction.tsx
- src/types.ts
Support for this feature was only added to the web console in version 4.18
> OLS-1351: Fix YAML import option to only be shown on 4.18+

- src/components/GeneralPage.tsx
- src/redux-actions.ts
- src/redux-reducers.ts
- src/types.ts
If you submitted a prompt while the previous response was still streaming, that previous response would get split across two entries in the chat.
> OLS-1490: Fix bug seen when submiting a prompt while a response is streaming

- src/components/GeneralPage.tsx
- src/types.ts
With the introduction of streaming, the response format changed from
`{"title": "...", "docs_url": "..."}`
to
`{"doc_title": "...", "doc_url": "..."}`
> OLS-1516: Fix reference doc links

- src/components/Feedback.tsx
- src/components/GeneralPage.tsx
Removing this because the auto-scroll had UX issues and also because the implementation was incorrect for responses other than the most recent.
> OLS-1491: Remove auto-scroll when feedback button is clicked

- src/components/GeneralPage.tsx
With the inclusion of OpenStack on top of the OpenShift Lightspeed and maybe more projects in the future, it's important to make these alert messages project agnostic.
This commit refactors the alert message to remove any project specific references.
> Remove project specific ref from alert message

- src/components/GeneralPage.tsx
- src/components/general-page.css
Minor style fix to improve the display on 4.19 without significantly changing the display in earlier versions.
> OLS-1748: Style fix for chat history "Context" on OpenShift 4.19

- .stylelintrc.yaml
- src/components/general-page.css
Fix some CSS variables to use PatternFly 5 names. These were using PatternFly 4 names, which will stop being available from 4.19.
Also makes a small fix for the chat history context padding on 4.18 and earlier.
> OLS-1748: CSS fixes for 4.19

- Dockerfile
Directed to stderr the nginx logs that are emitted before the nginx.conf config file is parsed. This is part of the switch to the read-only root filesystems for all the operands in the OLS operator, specifically to avoid the 
```
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (30: Read-only file system)
```
alert.
> OLS-1770: Add writable volumes to compensate for read-only root fs

- .env.example
- README.md
- cypress/support/commands.ts
- package-lock.json
- package.json
- src/components/AttachLogModal.tsx
- src/components/AttachMenu.tsx
- src/components/Feedback.tsx
- src/components/GeneralPage.tsx
- src/components/Popover.tsx
- src/components/ReadinessAlert.tsx
- src/config.ts
- src/hooks/useAuth.ts
- webpack.config.ts
These changes only affect the development environment.
- Adds `OLS_API_BASE_URL` environment variable for easily changing the OLS API location for local development and testing
- Renames `REACT_BEARER_TOKEN` environment variable to `OLS_API_BEARER_TOKEN`
- Removes `dotenv` package
> Simplify OLS API setup for development environment

- package-lock.json
- package.json
To avoid TypeScript error when running e2e tests with v5.0.0
> Downgrade @cypress/grep to v4.1.1
