- console-extensions.json
- package.json
- src/hooks/useAlertExtension.ts
The callback is just a placeholder for now to show that the integration works.
> Add Lightspeed action to alerts list dropdown

- Dockerfile
This is what the helm charts expect
> Change nginx sources dir back to /usr/share/nginx/html

- src/components/GeneralPage.tsx
- src/hooks/useBoolean.ts
Wording is just a TODO placeholder for now
> OLS-266: Add data privacy warnings

- src/components/GeneralPage.tsx
- webpack.config.ts
- Fix text not displaying in prompt input when typing
- Fix hot reload in dev environment
> Fixes for PatternFly 5 / plugin SDK v1.0.0 upgrade issues

- package.json
- src/components/GeneralPage.tsx
- yarn.lock
Also upgrades `@types/react` package to fix type error when using PatternFly icons
> Use paper plane icon for prompt submit button

- .eslintrc.yml
- .prettierrc.yml
- integration-tests/plugins/index.ts
- integration-tests/support/login.ts
- integration-tests/tests/example-page.cy.ts
- package.json
- src/components/GeneralPage.tsx
- src/hooks/useAlertExtension.ts
- src/hooks/usePodExtension.ts
- src/redux-actions.ts
- src/redux-reducers.ts
- yarn.lock
Use a print width of 100 chars to match the OpenShift console codebase.
> Lint fixes and add some additional lint rules

- start-console.sh
This resolves an error when developing on Apple Silicon machines
> Add `--platform linux/amd64` option to `docker run` command

- src/components/GeneralPage.tsx
Copy of @bparees's change from https://github.com/openshift/lightspeed-console/pull/29
> Fix request headers when calling OLS API

- src/components/GeneralPage.tsx
- src/redux-actions.ts
- src/redux-reducers.ts
So that the messages are not lost whenever the component is unmounted.
> Store current chat messages in Redux

- src/components/GeneralPage.tsx
- src/k8s.ts
When the current context is a pod, show the pod's current status in the chat popup.
> Add display for pod status

- src/components/GeneralPage.tsx
When a response from OLS contains a conversation_id, store it and send it back with the next request.
When the "New chat" button is clicked, clear the conversation_id so that the next request becomes a new conversation.
> OLS-395: Send the conversation_id back to OLS

- locales/en/plugin__lightspeed-console-plugin.json
- src/components/GeneralPage.tsx
- src/components/general-page.css
- src/redux-actions.ts
- src/redux-reducers.ts
Allow giving feedback on the quality of OLS responses.
The form is not yet connected to the user feedback API and the styling and wording used for the form will change.
> Add user feedback form

- package.json
- yarn.lock
Also a minor version update of dynamic-plugin-sdk-webpack to v1.0.1
> Upgrade to dynamic plugin SDK to v1.1.0

- src/components/GeneralPage.tsx
- src/components/general-page.css
Extracts the privacy alert into a separate component
> Add welcome screen for when the chat has not yet started

- README.md
Update the generic console plugin template info to be more specific to this plugin.
> Update README i18n section with this plugin's namespace

- start-console.sh
Same as https://github.com/openshift/lightspeed-console/pull/28, but for podman instead of docker
> Add --platform linux/amd64 option to podman run command

- package.json
- yarn.lock
Bump webpack-dev-server from 4.7.4 to 5.0.4
Bump webpack-cli from 4.9.2 to 5.1.4
> Upgrade webpack-dev-server and webpack-cli

- src/components/popover.css
Also increases the button size slightly and adjusts the popover UI margins to match the new margins of the launch button.
> Move launch button closer to the bottom, right corner

- src/redux-reducers.ts
Missed in https://github.com/openshift/lightspeed-console/pull/144
> Remove unused isPrivacyAlertDismissed flag from Redux

- package.json
- yarn.lock
Upgrade `cypress` to v13.11.0
Upgrade `eslint-plugin-cypress` to v3.3.0
Upgrade `@cypress/webpack-preprocessor` to v6.0.1
> Upgrade Cypress related dependencies to latest versions

- locales/en/plugin__lightspeed-console-plugin.json
- src/components/AttachEventsModal.tsx
- src/components/AttachLogModal.tsx
- src/components/AttachmentModal.tsx
- src/components/Modal.tsx
- src/components/NewChatModal.tsx
- src/components/general-page.css
Means that all modals now have a close button in the top right
> Refactor modals to use a common Modal component

- src/components/AttachmentModal.tsx
- src/components/GeneralPage.tsx
- src/components/general-page.css
Code block actions should be right aligned
> Fix copy code block action alignment

- Dockerfile
Added Labels in containerfile that is required for konflux release process
> [OLS-393]  added labels in container file for konflux

- locales/en/plugin__lightspeed-console-plugin.json
- src/components/AttachmentModal.tsx
- src/components/GeneralPage.tsx
- src/redux-actions.ts
- src/types.ts
After editing an attachment, save the original value and show a button that reverts the attachment back to its original value.
> OLS-565: Add ability to revert attachments back to their original value

- locales/en/plugin__lightspeed-console-plugin.json
- src/components/GeneralPage.tsx
- src/components/general-page.css
Also add " - modified" to the attachment label tooltip
> OLS-565: Add indicator to attachment label when attachment has been modified

- src/attachments.ts
- src/components/AttachmentModal.tsx
- src/components/CopyAction.tsx
- src/components/GeneralPage.tsx
- src/components/general-page.css
- Fix alignment so that the resource name and icon are on the left and the actions on the right
- Add icon to indicate when the attachment text has been edited
- Minor refactoring
> OLS-859: Code block header area improvements

- .tekton/lightspeed-console-pull-request.yaml
- .tekton/lightspeed-console-push.yaml
> Update konflux references

- src/components/OverviewDetail.tsx
> OLS 0.1.2 version update

- src/components/popover.css
Also includes some CSS changes to align with the floating Lightspeed button CSS used in the web console core
> OLS-472: Change floating button to single color version to support dark theme

- src/components/OverviewDetail.tsx
> OLS 0.1.3 version update

- src/components/OverviewDetail.tsx
> OLS 0.1.4 version update

- src/components/ReadinessAlert.tsx
> OLS-1006: Fix warning message when /ols/readiness check fails

- src/components/OverviewDetail.tsx
>  Update OLS version to 0.1.5

- src/components/OverviewDetail.tsx
Updated  version for 0.1.6 release
> Update  version for 0.1.6 release

- src/components/OverviewDetail.tsx
OLS 0.1.7 version update
JIRA: https://issues.redhat.com/browse/OLS-1083
> OLS 0.1.7 version update

- Dockerfile
Update nginx base image to nginx 1.24
> Update nginx base image to nginx 1.24

- src/hooks/useLocationContext.ts
Add the ability to attach the full YAML or just the YAML status section for pages under the Networking menu. Specifically, from the Ingress, NetworkPolicy, Route and Service details pages.
> OLS-1108: Add attach YAML for Ingress, NetworkPolicy, Route and Service

- src/components/OverviewDetail.tsx
> OLS 0.2.0 version update

- src/components/OverviewDetail.tsx
OLS release 0.2.1 version update
JIRA: https://issues.redhat.com/browse/OLS-1162
> OLS release 0.2.1 version update

- .tekton/lightspeed-console-pull-request.yaml
- .tekton/lightspeed-console-push.yaml
Disable build-source-image until [KFLUXBUGS-1508](https://issues.redhat.com//browse/KFLUXBUGS-1508) is fixed
JIRA: https://issues.redhat.com/browse/KFLUXBUGS-1508
> Disable build-source-image until KFLUXBUGS-1508 is fixed

- .gitignore
- cypress.config.ts
- cypress/support/commands.ts
- cypress/support/e2e.js
- package-lock.json
- package.json
- reporter-config.json
- tests/README.md
- tests/tests/lightspeed-install.cy.ts
- tests/views/operator-hub-page.ts
- tests/views/pages.ts
- tests/views/search.ts
- tests/views/utils.ts
- tsconfig.json
Migrating tests from openshift-tests-private
> OLS-742 - Migrating tests from openshift-tests-private

- locales/en/plugin__lightspeed-console-plugin.json
- src/components/GeneralPage.tsx
> OLS-1182: Add mailto link in UI footer for contacting OpenShift Lightspeed team

- src/components/AttachLogModal.tsx
- src/components/AttachMenu.tsx
- src/hooks/useLocationContext.ts
Adds attach Logs for VirtualMachines and VirtualMachineInstances
Fixes attach Events for VirtualMachines
Adds attach Events for VirtualMachineInstances
Adds attach YAML for VirtualMachineInstanceMigrations
> OLS-938: Add additional attach menu support for virtualization pages.

- .tekton/lightspeed-console-pull-request.yaml
- .tekton/lightspeed-console-push.yaml
[OLS-1256](https://issues.redhat.com//browse/OLS-1256): Add OLS ARM builds to Konflux
> OLS-1256: Add OLS ARM builds to Konflux

- .tekton/lightspeed-console-pull-request.yaml
- .tekton/lightspeed-console-push.yaml
Added project and org to the Konflux Snyk task so reports are pushed to snyk.io.
> OLS-1271: Added project and org to the Konflux Snyk task

- src/hooks/useLocationContext.ts
Instead of having a list of supported resource types, support all resource types returned by the plugin SDK's `useK8sModels` hook.
> OLS-1189: Generalize YAML attach functionality

- src/attachments.ts
- src/components/AttachMenu.tsx
Because it is no longer just the YAML status section, but also the YAML kind and metadata
> Change "YAML Status" attachment label to "YAML filtered"

- src/components/OverviewDetail.tsx
Bumped version to 0.3.0 for https://issues.redhat.com/browse/OLS-1274
> Bump to OLS version to 0.3.0

- .tekton/integration-tests/lightspeed-console-pre-commit-417.yaml
- tests/tests/lightspeed-install.cy.ts
Moved the operator installation from the first test to the before step.
Reason is that from my understanding, the second test started running before the first one finished, which was leading to us searching for elements with an old console plugin image. Some things have been renamed, therefore the tests failed.
Furthermore, due to the renamed elements, I adapted those test and it should now be passing.
> OLS-1348 - Adding pre-commit e2e UI tests

- src/components/OverviewDetail.tsx
Bump to version 0.3.1 for OLS release
> Bump to version 0.3.1

- .tekton/integration-tests/lightspeed-console-pre-commit-417.yaml
Adding awk install since nvm now requires it
> fixing tests 

- package-lock.json
- package.json
- src/hooks/useLocationContext.ts
Follow up to https://github.com/openshift/lightspeed-console/pull/720
> OLS-1658: Remove react-router and react-router-dom from package.json

- src/components/Feedback.tsx
- src/components/GeneralPage.tsx
- src/components/ResponseTools.tsx
Chip is replaced with Label in PatternFly 6, so this change will make upgrading slightly easier.
> OLS-1618: Replace Chip components with Label components

- src/components/AttachMenu.tsx
The whole SelectOption should be clickable, not just the icon and label
> OLS-1799: Fix clickable area for file upload option

- tests/tests/lightspeed-install.cy.ts
- tests/views/pages.ts
Also adds additional attach menu checks and some test refactoring.
> Allow all tests to be run independently of each other

- src/hooks/usePopover.ts
This ID keeps our UI separate from other web console modals
> OLS-1815: Pass unique ID to launchModal
